[env]
BROWSER = "firefox"
NOTEBOOK = "Project2.ipynb"

[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["start"]

[tasks.start]
command = "jupyter"
args = ["notebook", "--browser", "${BROWSER}", "${NOTEBOOK}"]
