[env]
BROWSER = "firefox"
NOTEBOOK = "Project2.ipynb"
FEEDBACK = "feedback.ipynb"

[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["start"]

[tasks.start]
command = "jupyter"
args = ["notebook", "--browser", "${BROWSER}", "${NOTEBOOK}"]

[tasks.feedback]
command = "jupyter"
args = ["notebook", "--browser", "${BROWSER}", "${FEEDBACK}"]
